version: '2'

services:
  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=persondata
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
    - ../../../storage/dockerdata/mysql:/var/lib/mysql

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: persondata
    # not available in version 2
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http:localhost"]
      #interval: 1m30s
      #timeout: 10s
      #retries: 3
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
#    environment:
      #- "SPRING_PROFILES_ACTIVE=default" specified in Dockerfile (can be specified here as well)


