version: '2'

networks:
  bridge:
    driver: bridge

services:
  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=persondata
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
    - ../../../storage/dockerdata/mysql:/var/lib/mysq

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: persondata
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=persondata
      - DATABASE_PORT=3306
      #- "SPRING_PROFILES_ACTIVE=default" specified in Dockerfile (can be specified here as well)