version: '2'

networks:
  bridge:
    driver: bridge

services:
  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=persondata
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
#TODO ADD VOLUME
  myapp-main:
    image: persondata
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=persondata
      - DATABASE_PORT=3306